services:
    cobalt-bypass:
        build:
            context: .
            args:
                HOST: 0.0.0.0
                PORT: 8080
                TURNSTILE_SOLVER_HOST: 100.126.105.31
                TURNSTILE_SOLVER_PORT: 12847
                COBALT_API_URL: https://api.cobalt.tools # WITHOUT TRAILING SLASH
        image: cobalt-bypass
        container_name: cobalt-bypass
        restart: unless-stopped
        #ports:
        #    - 8080:8080

networks:
  default:
    name: nginx
    external: true
